name: cosign

on: [push]

env:
  VERSION_MAJOR: 0
  VERSION_MINOR: 1
  VERSION_REV: $GITHUB_RUN_ID
  CONTAINER_NAME: sigstore

jobs:
  cosign:
    runs-on: ubuntu-latest

    steps:
        - uses: sigstore/cosign-installer@main